# Generated by Django 5.1.1 on 2024-10-18 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_frase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnosjaja'},
        ),
        migrations.AlterModelTable(
            name='alumno',
            table='Alumnos',
        ),
    ]
